apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    name: app
spec:
  containers:
  - name: app
    image: gcr.io/google_containers/mounttest:0.2
    args:
    - "sleep"
    - "1000000"
    volumeMounts:
    - mountPath: /mypath
      name: git-volume
  volumes:
  - name: git-volume
    gitRepo:
      repository: "http://127.0.0.1:8000"
      directory: "test"

