apiVersion: v1
kind: Service
metadata:
  name: gitsvc
  labels:
    name: app
spec:
  ports:
    # the port that this service should serve on
  - port: 2345
    targetPort: 8000
  selector:
    name: app
